version: '3.8'

services:
  db:
    image: postgres:latest
    volumes: 
      - ../ps_backup/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: ./.env_db
    restart: always
  
  web:
    build: .
    command: bash -c "alembic upgrade head && uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file: ./.env_db
    depends_on:
      - db
    restart: always
    stdin_open: true # for ipdb
    tty: true # for ipdb
  